### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by carolinomv** [gxapplications/myfox-wrapper-api#13]
nothing is available on wiki. I'm no able to run this package.

**Comment by gxapplications** [comment]
Hello,
There is nothing on the wiki to run the package, but install process is described in the Readme:
https://github.com/gxapplications/myfox-wrapper-api/blob/master/README.md#quick-start-guide

Or you can use the groc documentation here :
http://gxapplications.github.io/myfox-wrapper-api/groc/

**Comment by carolinomv** [comment]
Hello,

I’m sorry, i’m throuly inexperient on this. Is it possible tu run this wrapper on homebridge. how!
Thanks

**Comment by gxapplications** [comment]
Not at all, it's a library for developers who wish to build code calling myfox APIs in their own applications. I'm not related to homebridge at all.

For now it was used by my own application, no other developers made it compatible with their own application (including homebridge) as far as I know.

Notice if you're developer, this lib development is for now stopped for both reasons:
- Myfox enterprise was bought by Somfy ; the "MyFox Home 2" product is not sold anymore for years now, and then this lib won't be very useful in the futur (no new users, the Home 2 product is not maintained anymore by Myfox/Somfy for 3 years now).
- I stopped my own application (https://github.com/gxapplications/domotics-dashboard) using this library, for performances reasons. The next version of my application is here (https://github.com/gxapplications/asterism), but cannot use myfox wrapper yet (still in dev, alpha release only, need to wait several months...)

**Comment by carolinomv** [comment]
Ok. So you don't know any way that permit Home 2 to communicate with Apple Home App, do you?

**Comment by gxapplications** [comment]
I'm pretty sure there very few ways except with official Myfox applications, because
- the use of official Myfox API is restricted by Myfox itself (terms and use of conditions for example, are too strict: https://api.myfox.me/dev/terms, and very few functional possibilities)
- my wrapper is the only that I know that uses an HTTP robot to bypass the API restrictions simulating a real user.

You should try to find a list of compatible applications that uses this API to know if there is a solution for you: https://api.myfox.me/

**Comment by carolinomv** [comment]
the app that you create, how do you use it?

**Comment by gxapplications** [comment]
It's a web server based. You need to run it under nodejs / npm on a small server inside your house's network (a raspberry for example). Then an interface can control a lot of things from a web browser (on tablet, mobile phone, computer), like a dashboard. It cannot be used outside of the house.

But domotics-dashboard is not completely finished. I aborted it to make a v2: asterism.
asterism will be used the same way, but for now is in dev stage only: you cannot do anything with it today, dev takes a long time...

For more details, visit the old one: 
https://github.com/gxapplications/domotics-dashboard

And the new one:
https://github.com/gxapplications/asterism
